services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CACHE_URL=${CACHE_URL}
    networks:
      - app-network

networks:
  app-network:
