services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    volumes:
      - db_prod_data:/var/lib/postgresql/data
      - ./db/init_prod.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  cache:
    image: redis:alpine
    environment:
      - REDIS_HOST=cache
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  db_prod_data:

networks:
  app-network:
